### ISSUE TITLE
format_csv() prints null, when a variable referenced in the column list does not exist in the value list

### ISSUE THREAD

**Issue by jszigetvari** [axoflow/axosyslog#146]
# AxoSyslog
## Version of AxoSyslog
```
http://ghcr.io/axoflow/axosyslog:4.7.1_git20240605
```

## Platform
docker, amd64

## Debug bundle
N/A

## Steps to reproduce
When using format_csv(), and setting both the values and column_list, if some values referenced in the column list, do not exist in the values, then format_csv() will print a `null` string for that value.
The behavior should be to print nothing (empty string) for a specific undefined variable or one with no associated value.

**Comment by alltilla** [comment]
Fixed by #150
