### ISSUE TITLE
lots of CVEs in axosyslog 4.7.1

### ISSUE THREAD

**Issue by ikheifets-splunk** [axoflow/axosyslog#186]
<img width="805" alt="Screenshot 2024-07-04 at 11 44 53" src="https://github.com/axoflow/axosyslog/assets/138466237/8596064a-43bf-4d82-88b3-ed9494bfd60e">

More details you can find here [security issue](https://github.com/axoflow/axosyslog/security/advisories/GHSA-49fp-2pgm-44jp)

**Comment by ikheifets-splunk** [comment]
Made PR with upgrading `alpine linux` version. 
`requests` and `urllib3` already upgraded by dependabot 2 weeks ago

**Comment by ikheifets-splunk** [comment]
@MrAnno @bazsi what do you think if we will add on pipeline CVE detection of your docker image?

**Comment by ikheifets-splunk** [comment]
@alltilla Thanks for merging PR. When you planning to release it? You know it's security fix, and we don't know when 4.8.0 will be available :)

P.S. What do you think if we will add on pipeline automatic CVE detection of docker image? For example we on [CI](https://github.com/splunk/splunk-connect-for-syslog/blob/main/.github/workflows/ci-main.yaml#L157) using [trivy](https://trivy.dev)

**Comment by alltilla** [comment]
Hi @ikheifets-splunk 

4.8.0 is on its way: https://github.com/axoflow/axosyslog/pull/189 :)
ETA tomorrow or beginning of next week.

> P.S. What do you think if we will add on pipeline automatic CVE detection of docker image? For example we on [CI](https://github.com/splunk/splunk-connect-for-syslog/blob/main/.github/workflows/ci-main.yaml#L157) using [trivy](https://trivy.dev/)

Sounds reasonable, let's create a feature request for it.

**Comment by alltilla** [comment]
https://github.com/axoflow/axosyslog/issues/190

**Comment by ikheifets-splunk** [comment]
Released on 4.8.0
