### ISSUE TITLE
2 high CVEs on docker image 

### ISSUE THREAD

**Issue by ikheifets-splunk** [axoflow/axosyslog#67]
`Docker scout` finding 2 high vulnerabilities in docker image.
Just run command `docker scout cves ghcr.io/axoflow/axosyslog:4.6.0`.

<img width="720" alt="Screenshot 2024-03-19 at 12 45 39" src="https://github.com/axoflow/axosyslog/assets/138466237/49c0c29b-a2ea-4986-bbcc-930a095a0600">

**Comment by ikheifets-splunk** [comment]
@MrAnno @alltilla jfyi

**Comment by bazsi** [comment]
This is roughly just a rebuild away, which happens regularly at new
releases.

We could cut an earlier release though.

**Comment by MrAnno** [comment]
We have updated the 4.6.0 image.
There is also an ongoing PR to switch to `alpine:3.19 `: #68

**Comment by ikheifets-splunk** [comment]
Many thanks, @MrAnno @bazsi !
I will wait next release :) I think we can close this task.

**Comment by bazsi** [comment]
This image should contain the fixes already: https://github.com/axoflow/axosyslog/pkgs/container/axosyslog/193934484?tag=4.6.0
